### PR TITLE
Testing if this hans inline feedback

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by AJenbo** [comment]
Never mind it doesn't run on PR :/

**Comment by g105b** [comment]
Is there anything I can help you with, @AJenbo ?

**Comment by AJenbo** [comment]
Thanks, but I think the issue is simply that line line comments is not available for free private repos.

**Comment by g105b** [comment]
OK, please let me know if you need any help - happy to assist with anything PHPStan related.

**Pull request closed without merging**
